---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LAB.
--- DateTime: 2021/8/10 20:26
---
function callback(a, b)
    --error("ha")
    print("中午根本")
    return a * b * a+9
end

color = { red = 11, green = 10, blue = 9 }
