---
--- Generated by Luanalysis
--- Created by Vin.
--- DateTime: 2021/8/3 20:12
---
local test = require("test")

print(test.add(1, 2))
print(test.sub(1, 2))
print(test.sin(1))
print(test.message("naive","angry",4))